   
REM ################################################################################
REM ##   ____  ____ 
REM ##  /   /\/   / 
REM ## /___/  \  /    Vendor: Xilinx 
REM ## \   \   \/     Version : 1.11
REM ##  \   \         Application : Spartan-6 FPGA GTP Transceiver Wizard
REM ##  /   /         Filename : simulate_isim.bat
REM ## /___/   /\     
REM ## \   \  /  \ 
REM ##  \___\/\___\ 
REM ##
REM ##
REM ## Script SIMULATE_ISIM.BAT
REM ## Generated by Xilinx Spartan-6 FPGA GTP Transceiver Wizard

REM ***************************** Beginning of Script ***************************
        
mkdir work
REM MGT Wrapper
vlogcomp -work work  ..\..\..\gtp_tile.v
vlogcomp -work work  ..\..\..\gtp.v

vlogcomp -work work  ..\..\example_design\mgt_usrclk_source_pll.v

REM Example Design modules
vlogcomp -work work  ..\..\example_design\frame_gen.v
vlogcomp -work work  ..\..\example_design\frame_check.v
vlogcomp -work work  ..\..\example_design\gtp_top.v


REM Other modules
vlogcomp -work work  %XILINX%\verilog\src\glbl.v

REM Testbench file
vlogcomp -work work  ..\demo_tb.v


REM Compile and link source files
fuse work.DEMO_TB work.glbl -L unisims_ver -L secureip -o demo_tb.exe

REM ##--Generate waveform trace--##
.\demo_tb.exe -gui -tclbatch wave_isim.tcl -wdb wave_isim

